### PR TITLE
replace tape with m.test

### PR DESCRIPTION
**Pull request by christian-fei**

### CODE REVIEW

**Comment by mcollina** [comment]
@christian-fei why? this library can easily run Node v0.10+, and I see no reason to move to ES6 only code for a test runner.

**Comment by mcollina** [comment]
If you want to contribute to OSS, I have plenty of projects that needs help :D, including Node core.

**Comment by tunnckoCore** [comment]
@christian-fei don't see any value. Also when you commit to some project, just separate the commits. In this commit you don't just change the testing part, but use destructing to get the `createReadStream`.

:-1: it may `m.test` be cool lib (seen the code, not so amazing), but just random commit in some randomly picked library is not the right move. GL in OSS in anyway :)

@mcollina, which ones? I'm too busy too, but just curious and maybe can look for some more time.

**Comment by tunnckoCore** [comment]
@christian-fei for same reason, i can PR in dozen of libs to use [mukla](https://github.com/tunnckoCore/mukla) which is pretty stable for years and can be drop-in replacement for tape/mocha. But I didn't do that :)

**Comment by ivoputzer** [comment]
it's quite embarrassing how arrogant both of you replied to someone who spent it's spare time to come up with some new proposals in a constructive manner! kudos! this is what open source is all about, right?

@tunnckoCore i just take your comment as an educated opinion, hence there is no constructive statement whatsoever. `mukla` and `m.test` have a different aims, if your are willing to contribute for the better i bet you know the tools to do so ;) 

**if i was new to the node community answers like this would discourage me from contributing to any project. respect and constructive collaboration should be the baseline!**

Cheers! :+1:

**Comment by tunnckoCore** [comment]
I don't want to go too offtopic, but don't like to not try to clarify.

Arrogant? I don't see anything arrogant. We both just asked WHYs and WHATs as any normal maintainer or interested/watching dev.

> this is what open source is all about, right?

Yea, totally. But no one likes commits to contain more than what message says. 

Self point: Absolutely hate that everyone (new or not so new) should be treated like sweety little 1 year old puppy. And if one is new, it not means that we all others should forgive him. We all are busy, all have some style, habits, conventions, commit preferences and etc. If one is considering to contribute it should have some brain or at least to read if there is anything to read in the repo (like contributing guide and etc, in some cases there are no such files, okey) - as last resort first open an issue and discuss.
I learned a lot in the same way, and now few years later i have same preferences - first read, then try to discuss. I kinda don't see that as a big barrier for newcomers - we all are humans and so we can read, so let's do that first :)

:beers: Charlike

**Comment by ivoputzer** [comment]
@tunnckoCore to me your previous message isn't even worth a reply! i am not talking about habits, being busy nor treating people like a one year old puppy... respect and language are indeed a big barrier for newcomers! btw, thanks for pointing out the brainless people!

**Comment by mcollina** [comment]
@ivoputzer I'm sorry you think so bad about the Node community, and I'm sorry my comment was perceived as arrogant.

Let me explain what it is happening here: someone asks me to change one of libraries, without providing any reason for that change, or discussing it before on an issue. To be clear, this is not a bugfix. Moreover, as an OSS author I have no obbligation to accept any contribution.
I accept most of what is offered, and I provide code reviews and guidance.

I still fail to see an answer for "why" for this change. As I suspected it was done to make an OSS contribution, I pointed out that I crave for help with 200+ modules to maintain.

I'd gently ask everybody to self-moderate your post as they all violates any possible code of conduct I could think of, and remove all the offensive wording before I do it later on today. Thanks

**Comment by ivoputzer** [comment]
@mcollina i don't have any problem with the node community itself. i'm just saying that a simple "no thanks!" would have been way more effective than all of the above!

**Comment by tunnckoCore** [comment]
@christian-fei sorry if you feel it hard, it just not my native language. And in any way, i'm not talking about you exactly, i'm talking in general how I feel the whole community and seeing such scenarios everywhere. All I'm talking about is that you can't just push something like that and expect different answers than or at least simple "why" by the author.

> way more effective than all of the above!

What is "all of the above" - author asked from the first comment - Why is this change? I just joined to say that you can't expect different answer than that. :)

> @mcollina: someone asks me to change one of libraries, without providing any reason for that change, or discussing it before on an issue.

exactly what i'm talking about.

**Comment by mcollina** [comment]
@ivoputzer asking "why" gives an opportunity to express the reasons that brought to propose this change. This PR description is empty.

**Comment by ivoputzer** [comment]
@christian-fei `m.test` is meant to be compatible with maintained node versions only; this module inevitably does stick with legacy so i'd just leave it by that :)  anyways, thanks for giving `m.test` a try and for showing us yet another working example 👍

**Comment by christian-fei** [comment]
thanks everyone

**Pull request closed without merging**
